
import java.awt.Color;
import javax.swing.BorderFactory;

/*
 * -VERSION HISTORY-
*V 1.0 (2019.11.5): 1. Basic GUI components added: jLabel, JTextArea, jButton --> displays plain text to user and disposes of form
                                             2. Instantiates MainScren interface when closed and returns on click of button
*V2.0 (2019.11.7): Sets visibility as false and returns to previous interface screen w/out instantiation of previous form 
 */

/**
 * Displays instructions for user regarding game functionalities
 * @bashsaji161@granderie.ca 2019.11.18
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.white));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        InstructionsText = new javax.swing.JTextArea();
        Title = new javax.swing.JLabel();
        Close = new javax.swing.JButton();
        AestheticLine2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(51, 51, 51));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InstructionsText.setBackground(new java.awt.Color(0, 0, 0));
        InstructionsText.setColumns(20);
        InstructionsText.setFont(new java.awt.Font("Goudy Old Style", 0, 22)); // NOI18N
        InstructionsText.setForeground(new java.awt.Color(238, 238, 238));
        InstructionsText.setLineWrap(true);
        InstructionsText.setRows(5);
        InstructionsText.setText("The objective of the guessing game is to simply guess the correct number! You must first choose the number of guesses you would like to guess within by simply sliding your mouse along the slider. Afterwards, you must type in your guess that is within the guess range. You will be told whether your guess is too high, or too low.  You will be scored based on how many guesses you take to find the right number! Score high enough, and you'll find your name on the leaderboard!");
        InstructionsText.setWrapStyleWord(true);
        Background.add(InstructionsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 430, -1));

        Title.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Help");
        Background.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Close.setBackground(new java.awt.Color(255, 164, 63));
        Close.setFont(new java.awt.Font("Goudy Old Style", 3, 18)); // NOI18N
        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setText("Back ");
        Close.setToolTipText("");
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        Background.add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 80, -1));

        AestheticLine2.setBackground(new java.awt.Color(255, 255, 255));
        AestheticLine2.setPreferredSize(new java.awt.Dimension(0, 5));
        AestheticLine2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout AestheticLine2Layout = new javax.swing.GroupLayout(AestheticLine2);
        AestheticLine2.setLayout(AestheticLine2Layout);
        AestheticLine2Layout.setHorizontalGroup(
            AestheticLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        AestheticLine2Layout.setVerticalGroup(
            AestheticLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Background.add(AestheticLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        //hides help frame and returns 
        this.hide();
    }//GEN-LAST:event_CloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AestheticLine2;
    private javax.swing.JPanel Background;
    private javax.swing.JButton Close;
    private javax.swing.JTextArea InstructionsText;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
